name: Sync
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install requests
      - run: python3 run.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update
          add: dist/db.json
