name: 生成 IPTVINDEX 标准格式 db.json
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 生成标准 db.json
        run: |
          mkdir -p dist
          echo '{
    "urls": [
        {
            "name": "自动更新源",
            "url": "https://ghproxy.net/raw.githubusercontent.com/yangh909/tvbox-sync/main/dist/db.json"
        }
    ],
    "sites": [
        {
            "key": "bilibili",
            "name": "哔哩哔哩",
            "type": 3,
            "api": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/gaotianliuyun/gao/master/哔哩哔哩.js",
            "searchable": 1,
            "quickSearch": 1
        },
        {
            "key": "wanxiang",
            "name": "万向影视",
            "type": 3,
            "api": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/gaotianliuyun/gao/master/万向影视.js",
            "searchable": 1,
            "quickSearch": 1
        }
    ],
    "parses": [
        {
            "name": "通用解析",
            "url": "https://jx.qqzi.cn/jx.php?url="
        }
    ]
}' > dist/db.json

      - name: 提交更新
        uses: EndBug/add-and-commit@v9
        with:
          message: "✅ 自动更新 db.json"
          add: "dist/*"
